"use strict";(self.webpackChunkzio_site=self.webpackChunkzio_site||[]).push([[6447],{28453:(e,n,a)=>{a.d(n,{R:()=>r,x:()=>c});var t=a(96540);const s={},i=t.createContext(s);function r(e){const n=t.useContext(i);return t.useMemo((function(){return"function"==typeof e?e(n):{...n,...e}}),[n,e])}function c(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(s):e.components||s:r(e.components),t.createElement(i.Provider,{value:n},e.children)}},67332:(e,n,a)=>{a.r(n),a.d(n,{assets:()=>l,contentTitle:()=>c,default:()=>p,frontMatter:()=>r,metadata:()=>t,toc:()=>o});const t=JSON.parse('{"id":"reference/core/cause","title":"Cause","description":"The ZIO[R, E, A] effect is polymorphic in values of type E and we can work with any error type that we want, but there is a lot of information that is not inside an arbitrary E value. So as a result ZIO needs somewhere to store things like unexpected errors or defects, stack and execution traces, cause of fiber interruptions, and so forth.","source":"@site/docs/reference/core/cause.md","sourceDirName":"reference/core","slug":"/reference/core/cause","permalink":"/reference/core/cause","draft":false,"unlisted":false,"editUrl":"https://github.com/zio/zio/edit/series/2.x/docs/reference/core/cause.md","tags":[],"version":"current","frontMatter":{"id":"cause","title":"Cause"},"sidebar":"reference-sidebar","previous":{"title":"Exit","permalink":"/reference/core/exit"},"next":{"title":"Control Flow","permalink":"/reference/control-flow/"}}');var s=a(74848),i=a(28453);const r={id:"cause",title:"Cause"},c=void 0,l={},o=[{value:"Cause Internals",id:"cause-internals",level:2},{value:"Cause Variations",id:"cause-variations",level:2},{value:"Empty",id:"empty",level:3},{value:"Fail",id:"fail",level:3},{value:"Die",id:"die",level:3},{value:"Interrupt",id:"interrupt",level:3},{value:"Stackless",id:"stackless",level:3},{value:"Both",id:"both",level:3},{value:"Then",id:"then",level:3}];function d(e){const n={code:"code",em:"em",h2:"h2",h3:"h3",p:"p",pre:"pre",strong:"strong",...(0,i.R)(),...e.components};return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(n.p,{children:["The ",(0,s.jsx)(n.code,{children:"ZIO[R, E, A]"})," effect is polymorphic in values of type ",(0,s.jsx)(n.code,{children:"E"})," and we can work with any error type that we want, but there is a lot of information that is not inside an arbitrary ",(0,s.jsx)(n.code,{children:"E"})," value. So as a result ZIO needs somewhere to store things like ",(0,s.jsx)(n.strong,{children:"unexpected errors or defects"}),", ",(0,s.jsx)(n.strong,{children:"stack and execution traces"}),", ",(0,s.jsx)(n.strong,{children:"cause of fiber interruptions"}),", and so forth."]}),"\n",(0,s.jsxs)(n.p,{children:["ZIO is very strict about preserving the full information related to a failure. It captures all type of errors into the ",(0,s.jsx)(n.code,{children:"Cause"})," data type. ZIO uses ",(0,s.jsx)(n.code,{children:"Cause[E]"})," to store the full story of failure, so its error model is ",(0,s.jsx)(n.strong,{children:"lossless"}),". It doesn't throw away information related to the failure result. So we can figure out exactly what happened during the operation of our effects."]}),"\n",(0,s.jsxs)(n.p,{children:["It is important to note that ",(0,s.jsx)(n.code,{children:"Cause"})," is the underlying data type for the ZIO data type, and we don't usually deal with it directly. Even though we do not deal with it very often, anytime we want, we can access the ",(0,s.jsx)(n.code,{children:"Cause"})," data structure, which gives us total access to all parallel and sequential errors in our codebase."]}),"\n",(0,s.jsx)(n.h2,{id:"cause-internals",children:"Cause Internals"}),"\n",(0,s.jsxs)(n.p,{children:["ZIO uses a data structure from functional programming called a ",(0,s.jsx)(n.em,{children:"semiring"})," for the ",(0,s.jsx)(n.code,{children:"Cause"})," data type. ",(0,s.jsxs)(n.strong,{children:["It allows us to take a base type ",(0,s.jsx)(n.code,{children:"E"})," that represents the error type and then capture the sequential and parallel composition of errors in a fully lossless fashion"]}),"."]}),"\n",(0,s.jsxs)(n.p,{children:["The following snippet shows how ",(0,s.jsx)(n.code,{children:"Cause"})," is designed as a semiring data structure:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:"sealed abstract class Cause[+E] extends Product with Serializable { self =>\n  import Cause._\n  def trace: Trace = ???\n\n  final def ++[E1 >: E](that: Cause[E1]): Cause[E1] = Then(self, that)\n  final def &&[E1 >: E](that: Cause[E1]): Cause[E1] = Both(self, that)\n}\n\nobject Cause extends Serializable {\n  case object Empty extends Cause[Nothing]\n  final case class Fail[+E](value: E, override val trace: Trace) extends Cause[E]\n  final case class Die(value: Throwable, override val trace: Trace) extends Cause[Nothing]\n  final case class Interrupt(fiberId: FiberId, override val trace: Trace) extends Cause[Nothing]\n  final case class Stackless[+E](cause: Cause[E], stackless: Boolean) extends Cause[E]\n  final case class Then[+E](left: Cause[E], right: Cause[E]) extends Cause[E]\n  final case class Both[+E](left: Cause[E], right: Cause[E]) extends Cause[E]\n}\n"})}),"\n",(0,s.jsxs)(n.p,{children:["Using the ",(0,s.jsx)(n.code,{children:"Cause"})," data structure described above, ZIO can capture all errors inside the application."]}),"\n",(0,s.jsx)(n.h2,{id:"cause-variations",children:"Cause Variations"}),"\n",(0,s.jsx)(n.p,{children:"There are several causes for various errors. In this section, we will describe each of these causes. We will see how they can be created manually or how they will be automatically generated as the underlying error management data type of a ZIO application."}),"\n",(0,s.jsx)(n.h3,{id:"empty",children:"Empty"}),"\n",(0,s.jsxs)(n.p,{children:["The ",(0,s.jsx)(n.code,{children:"Empty"})," cause indicates the lack of errors. We use ",(0,s.jsx)(n.code,{children:"Cause.empty"})," constructor to create an ",(0,s.jsx)(n.code,{children:"Empty"})," cause. Using ",(0,s.jsx)(n.code,{children:"ZIO.failCause"})," we can create a ZIO effect that has an empty cause:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:"import zio._\n\nZIO.failCause(Cause.empty).cause.debug\n// Empty\n"})}),"\n",(0,s.jsxs)(n.p,{children:["Also, we can use ",(0,s.jsx)(n.code,{children:"ZIO#cause"})," to uncover the underlying cause of an effect. For example, we know that ",(0,s.jsx)(n.code,{children:"ZIO.succeed(5)"})," has no errors. So, let's check that:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{children:"ZIO.succeed(5).cause.debug\n// Empty\n\nZIO.attempt(5).cause.debug\n// Empty\n"})}),"\n",(0,s.jsx)(n.h3,{id:"fail",children:"Fail"}),"\n",(0,s.jsxs)(n.p,{children:["The ",(0,s.jsx)(n.code,{children:"Fail"})," cause indicates the cause of an ",(0,s.jsx)(n.em,{children:"expected error"})," of type ",(0,s.jsx)(n.code,{children:"E"}),". We can create one using the ",(0,s.jsx)(n.code,{children:"Cause.fail"})," constructor:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nZIO.failCause(Cause.fail("Oh uh!")).cause.debug\n// Fail(Oh uh!,Trace(Runtime(2,1646395282),Chunk(<empty>.MainApp.run(MainApp.scala:4))))\n'})}),"\n",(0,s.jsx)(n.p,{children:"Let's uncover the cause of some ZIO effects especially when we combine them:"}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nZIO.fail("Oh uh!").cause.debug\n// Fail(Oh uh!,Trace(Runtime(2,1646395627),Chunk(<empty>.MainApp.run(MainApp.scala:3))))\n\n(ZIO.fail("Oh uh!") *> ZIO.dieMessage("Boom!") *> ZIO.interrupt).cause.debug\n// Fail(Oh uh!,Trace(Runtime(2,1646396370),Chunk(<empty>.MainApp.run(MainApp.scala:6))))\n\n(ZIO.fail("Oh uh!") <*> ZIO.fail("Oh Error!")).cause.debug\n// Fail(Oh uh!,Trace(Runtime(2,1646396419),Chunk(<empty>.MainApp.run(MainApp.scala:9))))\n\nval myApp: ZIO[Any, String, Int] =\n  for {\n    i <- ZIO.succeed(5)\n    _ <- ZIO.fail("Oh uh!")\n    _ <- ZIO.dieMessage("Boom!")\n    _ <- ZIO.interrupt\n  } yield i\nmyApp.cause.debug\n// Fail(Oh uh!,Trace(Runtime(2,1646397126),Chunk(<empty>.MainApp.myApp(MainApp.scala:13),<empty>.MainApp.run(MainApp.scala:17))))\n'})}),"\n",(0,s.jsx)(n.h3,{id:"die",children:"Die"}),"\n",(0,s.jsxs)(n.p,{children:["The ",(0,s.jsx)(n.code,{children:"Die"})," cause indicates a defect, an ",(0,s.jsx)(n.em,{children:"unexpected failure"})," of type ",(0,s.jsx)(n.code,{children:"Throwable"}),". It contains the stack trace of the defect that occurred. We can use ",(0,s.jsx)(n.code,{children:"Cause.die"})," to create one:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nZIO.failCause(Cause.die(new Throwable("Boom!"))).cause.debug\n// Die(java.lang.Throwable: Boom!,Trace(Runtime(2,1646479908),Chunk(<empty>.MainApp.run(MainApp.scala:3))))\n'})}),"\n",(0,s.jsxs)(n.p,{children:["If we have a bug in our code and something throws an unexpected exception, that information would be described inside a ",(0,s.jsx)(n.code,{children:"Die"}),". Let's try to investigate some ZIO code that will die:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nZIO.succeed(5 / 0).cause.debug\n// Die(java.lang.ArithmeticException: / by zero,Trace(Runtime(2,1646480112),Chunk(zio.internal.FiberContext.runUntil(FiberContext.scala:538),<empty>.MainApp.run(MainApp.scala:3))))\n\nZIO.dieMessage("Boom!").cause.debug\n// Stackless(Die(java.lang.RuntimeException: Boom!,Trace(Runtime(2,1646398246),Chunk(<empty>.MainApp.run(MainApp.scala:7)))),true)\n'})}),"\n",(0,s.jsxs)(n.p,{children:["It is worth noting that the latest example is wrapped by the ",(0,s.jsx)(n.code,{children:"Stackless"})," cause in the previous example. We will discuss ",(0,s.jsx)(n.code,{children:"Stackless"})," further, but for now, it is enough to know that ",(0,s.jsx)(n.code,{children:"Stackless"})," includes fewer stack traces than the ",(0,s.jsx)(n.code,{children:"Die"})," cause."]}),"\n",(0,s.jsx)(n.h3,{id:"interrupt",children:"Interrupt"}),"\n",(0,s.jsxs)(n.p,{children:["The ",(0,s.jsx)(n.code,{children:"Interrupt"})," cause indicates a fiber interruption which contains information of the ",(0,s.jsx)(n.em,{children:"fiber id"})," of the interrupted fiber, and also the corresponding stack trace. Let's try an example of:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:"import zio._\n\nZIO.interrupt.cause.debug\n// Interrupt(Runtime(2,1646471715),Trace(Runtime(2,1646471715),Chunk(<empty>.MainApp.run(MainApp.scala:3))))\n\nZIO.never.fork\n  .flatMap(f => f.interrupt *> f.join)\n  .cause\n  .debug\n// Interrupt(Runtime(2,1646472025),Trace(Runtime(13,1646472025),Chunk(<empty>.MainApp.run(MainApp.scala:7))))\n"})}),"\n",(0,s.jsx)(n.h3,{id:"stackless",children:"Stackless"}),"\n",(0,s.jsxs)(n.p,{children:["The ",(0,s.jsx)(n.code,{children:"Stackless"})," cause stores stack traces and execution traces. It has a boolean ",(0,s.jsx)(n.code,{children:"stackless"})," flag which denotes whether the ZIO runtime should print the full stack trace of the inner cause or just print a few lines of it."]}),"\n",(0,s.jsxs)(n.p,{children:["For example, ",(0,s.jsx)(n.code,{children:"ZIO.dieMessage"})," uses ",(0,s.jsx)(n.code,{children:"Stackless"}),":"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nZIO.dieMessage("Boom!").cause.debug\n// Stackless(Die(java.lang.RuntimeException: Boom!,Trace(Runtime(2,1646477970),Chunk(<empty>.MainApp.run(MainApp.scala:3)))),true)\n'})}),"\n",(0,s.jsx)(n.p,{children:"So when we run it the following stack traces will be printed:"}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'timestamp=2022-03-05T11:08:19.530710679Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-2" java.lang.RuntimeException: Boom!\nat <empty>.MainApp.run(MainApp.scala:3)"\n'})}),"\n",(0,s.jsxs)(n.p,{children:["While ",(0,s.jsx)(n.code,{children:"ZIO.die"})," doesn't use ",(0,s.jsx)(n.code,{children:"Stackless"})," cause:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nZIO.die(new Throwable("Boom!")).cause.debug\n// Die(java.lang.Exception: Boom!,Trace(Runtime(2,1646479093),Chunk(<empty>.MainApp.run(MainApp.scala:3))))\n'})}),"\n",(0,s.jsx)(n.p,{children:"So it prints the full stack trace:"}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'timestamp=2022-03-05T11:19:12.666418357Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-2" java.lang.Exception: Boom!\n\tat MainApp$.$anonfun$run$1(MainApp.scala:4)\n\tat zio.ZIO$.$anonfun$die$1(ZIO.scala:3384)\n\tat zio.internal.FiberContext.runUntil(FiberContext.scala:255)\n\tat zio.internal.FiberContext.run(FiberContext.scala:115)\n\tat zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)\n\tat <empty>.MainApp.run(MainApp.scala:4)"\n'})}),"\n",(0,s.jsx)(n.h3,{id:"both",children:"Both"}),"\n",(0,s.jsxs)(n.p,{children:["When we are doing parallel computation, the effect can fail for more than one reason. If we are doing two things at once and both of them fail then we actually have two errors. So, the ",(0,s.jsx)(n.code,{children:"Both"})," cause stores the composition of two parallel causes."]}),"\n",(0,s.jsxs)(n.p,{children:["For example, if we run two parallel fibers with ",(0,s.jsx)(n.code,{children:"zipPar"})," and all of them fail, their causes will be encoded with ",(0,s.jsx)(n.code,{children:"Both"}),":"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nval myApp: ZIO[Any, String, Unit] =\n  for {\n    f1 <- ZIO.fail("Oh uh!").fork\n    f2 <- ZIO.dieMessage("Boom!").fork\n    _ <- (f1 <*> f2).join\n  } yield ()\nmyApp.cause.debug\n// Both(Fail(Oh uh!,Trace(Runtime(13,1646481219),Chunk(<empty>.MainApp.myApp(MainApp.scala:5)))),Stackless(Die(java.lang.RuntimeException: Boom!,Trace(Runtime(14,1646481219),Chunk(<empty>.MainApp.myApp(MainApp.scala:6)))),true))\n'})}),"\n",(0,s.jsxs)(n.p,{children:["If we run the ",(0,s.jsx)(n.code,{children:"myApp"})," effect, in the stack trace we can see two exception traces occurred on two separate fibers:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'timestamp=2022-03-05T12:37:46.831096692Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-13" java.lang.String: Oh uh!\nat <empty>.MainApp.myApp(MainApp.scala:5)\n  Exception in thread "zio-fiber-14" java.lang.RuntimeException: Boom!\n  at <empty>.MainApp.myApp(MainApp.scala:6)"\n'})}),"\n",(0,s.jsxs)(n.p,{children:["Other parallel operators are also the same, for example, ZIO encodes the underlying cause of ",(0,s.jsx)(n.code,{children:'(ZIO.fail("Oh uh!") <&> ZIO.dieMessage("Boom!"))'})," with the ",(0,s.jsx)(n.code,{children:"Both"})," cause."]}),"\n",(0,s.jsx)(n.h3,{id:"then",children:"Then"}),"\n",(0,s.jsxs)(n.p,{children:["ZIO uses ",(0,s.jsx)(n.code,{children:"Then"})," cause to encode sequential errors. For example, if we perform ZIO's analog of ",(0,s.jsx)(n.code,{children:"try-finally"})," (e.g. ",(0,s.jsx)(n.code,{children:"ZIO#ensuring"}),"), and both ",(0,s.jsx)(n.code,{children:"try"})," and ",(0,s.jsx)(n.code,{children:"finally"})," blocks fail, their causes are encoded with ",(0,s.jsx)(n.code,{children:"Then"}),":"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'import zio._\n\nval myApp =\n  ZIO.fail("first")\n    .ensuring(ZIO.die(throw new Exception("second")))\n\nmyApp.cause.debug\n// Then(Fail(first,Trace(Runtime(2,1646486975),Chunk(<empty>.MainApp.myApp(MainApp.scala:4),<empty>.MainApp.myApp(MainApp.scala:5),<empty>.MainApp.run(MainApp.scala:7)))),Die(java.lang.Exception: second,Trace(Runtime(2,1646486975),Chunk(zio.internal.FiberContext.runUntil(FiberContext.scala:538),<empty>.MainApp.myApp(MainApp.scala:5),<empty>.MainApp.run(MainApp.scala:7)))))\n'})}),"\n",(0,s.jsxs)(n.p,{children:["If we run the ",(0,s.jsx)(n.code,{children:"myApp"})," effect, we can see the following stack trace:"]}),"\n",(0,s.jsx)(n.pre,{children:(0,s.jsx)(n.code,{className:"language-scala",children:'timestamp=2022-03-05T13:30:17.335173071Z level=ERROR thread=#zio-fiber-0 message="Exception in thread "zio-fiber-2" java.lang.String: first\n\tat <empty>.MainApp.myApp(MainApp.scala:4)\n\tat <empty>.MainApp.myApp(MainApp.scala:5)\n\tSuppressed: java.lang.Exception: second\n\t\tat MainApp$.$anonfun$myApp$3(MainApp.scala:5)\n\t\tat zio.ZIO$.$anonfun$die$1(ZIO.scala:3384)\n\t\tat zio.internal.FiberContext.runUntil(FiberContext.scala:255)\n\t\tat zio.internal.FiberContext.run(FiberContext.scala:115)\n\t\tat zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)\n\t\tat zio.internal.FiberContext.runUntil(FiberContext.scala:538)\n\t\tat <empty>.MainApp.myApp(MainApp.scala:5)"\n'})}),"\n",(0,s.jsxs)(n.p,{children:["As we can see in the above stack trace, the ",(0,s.jsx)(n.em,{children:"first"})," failure was suppressed by the ",(0,s.jsx)(n.em,{children:"second"})," defect."]})]})}function p(e={}){const{wrapper:n}={...(0,i.R)(),...e.components};return n?(0,s.jsx)(n,{...e,children:(0,s.jsx)(d,{...e})}):d(e)}}}]);